CREATE TABLE LICE(
  IDL VARCHAR2(8) NOT NULL,
  IMEL VARCHAR2(20) NOT NULL,
  PRZL VARCHAR2(20) NOT NULL,
  VRSTAL VARCHAR2(12) NOT NULL,
  MES_PRIHODIL DECIMAL(10, 2) NOT NULL,
  CONSTRAINT PK_LICE PRIMARY KEY (IDL),
  CONSTRAINT CH_VRSTAL CHECK (VRSTAL IN ('FIZICKO', 'PRAVNO'))
);

CREATE TABLE VRSTAOBJEKTA(
  IDVO INTEGER NOT NULL,
  NAZIVVO VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_VRSTAOBJEKTA PRIMARY KEY (IDVO)
);

CREATE TABLE OBJEKAT(
  IDO INTEGER NOT NULL,
  IDL VARCHAR2(8) NOT NULL,
  IDVO INTEGER NOT NULL,
  POVRSINA DECIMAL(10,2) NOT NULL,
  ADRESA VARCHAR2(100) NOT NULL,
  VREDNOST DECIMAL(10, 2) NOT NULL,
  CONSTRAINT PK_OBJEKAT PRIMARY KEY(IDO),
  CONSTRAINT FK_OBJEKAT_VRSTAOBJEKTA FOREIGN KEY (IDVO) REFERENCES VRSTAOBJEKTA(IDVO),
  CONSTRAINT FK_OBJEKAT_LICE FOREIGN KEY (IDL) REFERENCES LICE (IDL)
);

CREATE TABLE BILANSSTANJA(
  IDBS INTEGER NOT NULL,
  IDL VARCHAR(13) NOT NULL,
  SALDO DECIMAL (10,2) NOT NULL,
  DUG DECIMAL (10,2) NOT NULL,
  KAMATA DECIMAL (10,2),
  CONSTRAINT PK_BILANSSTANJA PRIMARY KEY(IDBS),
  CONSTRAINT FK_BILANSSTANJA_LICE FOREIGN KEY (IDL) REFERENCES LICE(IDL)
);